image: docker:git

stages:
  - build

echo-params:
  stage: build
  script:
    - echo "Build parameters:"
    - echo "DEPLOYMENTS_REV=${DEPLOYMENTS_REV}"
    - echo "DEVICEAUTH_REV=${DEVICEAUTH_REV}"
    - echo "GUI_REV=${GUI_REV}"
    - echo "MENDER_REV=${MENDER_REV}"
    - echo "MENDER_API_GATEWAY_DOCKER_REV=${MENDER_API_GATEWAY_DOCKER_REV}"
    - echo "MENDER_ARTIFACT_REV=${MENDER_ARTIFACT_REV}"
    - echo "MENDER_CLI_REV=${MENDER_CLI_REV}"
    - echo "MENDER_CONDUCTOR_REV=${MENDER_CONDUCTOR_REV}"
    - echo "MENDER_CONDUCTOR_ENTERPRISE_REV=${MENDER_CONDUCTOR_ENTERPRISE_REV}"
    - echo "USERADM_REV=${USERADM_REV}"
    - echo "INTEGRATION_REV=${INTEGRATION_REV}"
    - echo "BASE_BRANCH=${BASE_BRANCH}"
    - echo "RUN_INTEGRATION_TESTS=${RUN_INTEGRATION_TESTS}"
    - echo "INVENTORY_REV=${INVENTORY_REV}"
    - echo "BUILD_QEMUX86_64_UEFI_GRUB=${BUILD_QEMUX86_64_UEFI_GRUB}"
    - echo "TEST_QEMUX86_64_UEFI_GRUB=${TEST_QEMUX86_64_UEFI_GRUB}"
    - echo "BUILD_QEMUX86_64_BIOS_GRUB=${BUILD_QEMUX86_64_BIOS_GRUB}"
    - echo "TEST_QEMUX86_64_BIOS_GRUB=${TEST_QEMUX86_64_BIOS_GRUB}"
    - echo "BUILD_QEMUX86_64_BIOS_GRUB_GPT=${BUILD_QEMUX86_64_BIOS_GRUB_GPT}"
    - echo "TEST_QEMUX86_64_BIOS_GRUB_GPT=${TEST_QEMUX86_64_BIOS_GRUB_GPT}"
    - echo "BUILD_VEXPRESS_QEMU=${BUILD_VEXPRESS_QEMU}"
    - echo "TEST_VEXPRESS_QEMU=${TEST_VEXPRESS_QEMU}"
    - echo "BUILD_VEXPRESS_QEMU_FLASH=${BUILD_VEXPRESS_QEMU_FLASH}"
    - echo "TEST_VEXPRESS_QEMU_FLASH=${TEST_VEXPRESS_QEMU_FLASH}"
    - echo "BUILD_VEXPRESS_QEMU_UBOOT_UEFI_GRUB=${BUILD_VEXPRESS_QEMU_UBOOT_UEFI_GRUB}"
    - echo "TEST_VEXPRESS_QEMU_UBOOT_UEFI_GRUB=${TEST_VEXPRESS_QEMU_UBOOT_UEFI_GRUB}"
    - echo "BUILD_BEAGLEBONEBLACK=${BUILD_BEAGLEBONEBLACK}"

